services:
  nextcloud:
    image: nextcloud:28
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - db
      - redis
    volumes:
      - /data/nextcloud:/var/www/html
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_HOST=nextcloud-db

  nextcloud-db:
    image: mariadb:11
    container_name: nextcloud_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - /docker/nextcloud/db:/var/lib/mysql

  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud_redis
    restart: unless-stopped

  nextcloud-cron:
    image: nextcloud:28
    container_name: nextcloud_cron
    restart: unless-stopped
    entrypoint: /cron.sh
    depends_on:
      - nextcloud
    volumes:
      - /data/nextcloud:/var/www/html
